### ISSUE TITLE
MQ server TLS/SSL certificate

### ISSUE THREAD

**Issue by momipsl** [Prodiguer/prodiguer-docs#1] opened 2014-08-12 13:35 UTC
The Prodiguer MQ server needs to be secured at the transport level by applying a server TLS/SSL x509 certificate.

**Comment by momipsl** [comment] 2015-01-05 14:55
Need to ask @ncaripsl  whether he has a certificate to use for this purpose.

**Comment by ncaripsl** [comment] 2015-01-05 15:08
Yes, it has been installed on prodiguer-test-mq. The server is already listening on both amqp 5672 and amqp/ssl 5671

**Comment by momipsl** [comment] 2015-01-05 19:49
OK this means that we should remove the 5762 channel and update the prodiguer.json config files accordingly.

**Comment by momipsl** [comment] 2015-03-23 09:20
@SebastienDenvil The prodiguer.json files on the MQ server should be updated so that they use the AMPQS protocol.  Open the config file and edit the 2 connection strings defined within the config section mq.connections:

1.  Replace amqp with amqps.
2.  Replase 5672 with 5671.

**Comment by ncaripsl** [comment] 2015-03-27 16:13
Done on the test VM

**Comment by SebastienDenvil** [comment] 2015-03-27 20:27
Revert the change because emails are not consumed anymore.

Might be good to push that change on /opt/prodiguer/templates/config/prodiguer.json and then to upgrade the 3 servers (mq, fe, db).

**Comment by ncaripsl** [comment] 2015-03-30 15:12
Got this error after switching to 5671 in the config file:

=ERROR REPORT==== 30-Mar-2015::16:39:50 ===
SSL: 1112: error:[] /root/certif-ipsl.fr/prodiguer-test-mq.ipsl.fr.key
  [{ssl_connection,init_private_key,5},
   {ssl_connection,ssl_init,2},
   {ssl_connection,init,1},
   {gen_fsm,init_it,6},
   {proc_lib,init_p_do_apply,3}]

Solved this one by upgrading to erlang 17 from https://www.rabbitmq.com/releases/erlang/erlang-17.4-1.el6.x86_64.rpm

Then got a new error:

=ERROR REPORT==== 30-Mar-2015::16:45:37 ===
error on AMQP connection <0.538.0>:
{ssl_upgrade_error,{tls_alert,"record overflow"}}

Is there more config than the json file to setup ssl on the consumers side?

**Comment by momipsl** [comment] 2015-04-01 09:10
I will test the RabbitMQ upgrade to v3.5.0 with SSL connection from prodiguer python perspective in order to confirm that no coding changes are required and that a simple update of prodiguer.json config file is sufficient.

**Comment by momipsl** [comment] 2015-04-01 10:35
OK so I have upgraded to RabbitMQ v3.5.0 and the tests reported no problems.  Therefore the upgrade to v3.5.0 can go ahead from my perspective.  

Will now test the SSL setup / configuration.

**Comment by momipsl** [comment] 2015-04-01 12:55
OK so I:
1.  Created a test root authority certificate.
2.  Generated server & client certificates.
3.  Edited the rabbitmq.config file:
   {ssl_listeners, [5671]},
   {ssl_options, [{cacertfile,"PATH_TO_ROOT_AUTH_CERT_DIR/cacert.pem"},
                  {certfile,"PATH_TO_SERVER_CERT_DIR/cert.pem"},
                  {keyfile,"PATH_TO_SERVER_CERT_DIR/key.pem"},
                  {verify,verify_peer},
                  {fail_if_no_peer_cert,false}]}
4.  Restarted RabbitMQ server.
5.  Edited RabbitMQ connection strings in prodiguer.json file: replaced amp: with ampqs: and port 5672 with 5671.
6.  Tested MQ consumers.

All was good.  This is step 1 towards the full solution.  It is worth testing this now.  

The next step is to update the rabbitmq.config:ssl_options:fail_if_no_peer option to true.  This will require a code change so that the client ssl options are correctly specified when the Prodiguer MQ agents attempt to connect.  I will wait until step 1 is successfully deployed.

**Comment by momipsl** [comment] 2015-04-01 13:28
Step 2 is to do the following:
1.  mkdir -p /opt/prodiguer/ops/certs/rabbitmq
2.  Copy MQ client X509 **cert** file to: 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/opt/prodiguer/ops/certs/rabbitmq/client-cert.pem
3.  Copy MQ client X509 **key** file to:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/opt/prodiguer/ops/certs/rabbitmq/client-key.pem
4.   Suffix the MQ connection strings in /opt/prodiguer/ops/config/**prodiguer.json** with: 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ssl_options=%7B%27keyfile%27%3A+%27%2Fopt%2Fprodiguer%2Fops%2Fcerts%2Frabbitmq%2Fclient-key.pem%27%2C+%27certfile%27%3A+%27%2Fopt%2Fprodiguer%2Fops%2Fcerts%2Frabbitmq%2Fclient-cert.pem%27%7D

**Comment by momipsl** [comment] 2015-04-01 13:39
Once step 2 above is achieved then the 3rd and final step is to update the Rabbit MQ config file to tell the server only to accept SSL connections from clients that PRESENT A VALID CERTIFICATE:

1.  Edited the **rabbitmq.config** file:
&nbsp;&nbsp;&nbsp;{ssl_listeners, [5671]},
&nbsp;&nbsp;&nbsp;{ssl_options, [{cacertfile,"PATH_TO_ROOT_AUTH_CERT_DIR/cacert.pem"},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{certfile,"PATH_TO_SERVER_CERT_DIR/cert.pem"},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{keyfile,"PATH_TO_SERVER_CERT_DIR/key.pem"},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{verify,verify_peer},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{fail_if_no_peer_cert,**true**}]}
2.  Restart RabbitMQ server.
3.  Restart Prodiguer MQ agents:
&nbsp;&nbsp;&nbsp;source /opt/prodiguer/ops/venv/server/bin/activate
&nbsp;&nbsp;&nbsp;supervisorctl -c /opt/prodiguer/ops/config/mq-supervisord.conf restart all

**Comment by ncaripsl** [comment] 2015-04-03 14:36
The rabbitmq config file was already up to date with certs info. Step 1 is now achieved as I updated rabbitmq server to version 3.5 and erland to version 17.4 + modified the json config file. Messages are well consumed.

**Comment by ncaripsl** [comment] 2015-04-03 14:38
But there might be a regression on the consumers logging system as it seems new messages are not being logged anymore.

**Comment by SebastienDenvil** [comment] 2015-04-10 13:01
FYI the ext-smtp-realtime mails consumer has not been working for 2 days due to this error. It seems related to SSL.

We really need notification when a daemon exits like this.

2015-04-08T14:17:24.213052+00:00 :: IPSL PRODIGUER INFO MQ > 1 new messages for dispatch: [198142]
2015-04-08T14:17:24.235321+00:00 :: IPSL PRODIGUER INFO MQ > Dispatching email 198142 to MQ server
2015-04-08T14:17:56.395135+00:00 :: IPSL PRODIGUER INFO MQ > 1 new messages for dispatch: [198144]
2015-04-08T14:18:04.917001+00:00 :: IPSL PRODIGUER ERROR MQ > !!! MQ RUNTIME ERROR !!! :: <class 'pika.exceptions.AMQPConnectionError'> :: Connection to 127.0.0.1:5671 failed: _ssl.c:492: The handshake operation timed out.

**Comment by ncaripsl** [comment] 2015-04-13 10:21
Just asked ISIS if we could install NRPE in order to set up check_logfiles (http://labs.consol.de/nagios/check_logfiles/)

**Comment by ncaripsl** [comment] 2015-04-14 14:49
Just introduced nagios nrpe and check_logfiles plugin. It does already check for critical patterns  'exited' and 'FATAL' in supervisor.log but we can extend to other log files and configure rotation methods.

**Comment by SebastienDenvil** [comment] 2015-06-17 10:18
@ncaripsl can we close this one? Are new messages being logged with amqps?

**Comment by ncaripsl** [comment] 2015-06-17 12:28
Yes. But we still have this config on the server side {fail_if_no_peer_cert,true}]}. This can be anbled when the rabbitmq relay will be ready.

**Closed by ncaripsl** 2015-06-17 12:28 UTC
Labels: DevOps, feature, MQ server
