### ISSUE TITLE
The front-end is too slow when StartDate > 2 weeks

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#45] opened 2015-10-12 14:24 UTC
The front-end usability is very poor and practically unusable when StartDate > 2 weeks.
Pages take 25+ seconds to load when StartDate <1month

We need urgently to identify bottlenecks and to profile the application (having numbers) so as to find a solution. We might have to redesign if the current design can not over decent performances.

**Comment by momipsl** [comment] 2015-10-12 14:41
These are the main steps involved in displaying the timeslice and are the source of potential bottle-necks:
 
Server side:
1.  Parse HTTP request parameters.
2.  Issue SQL request over network (web-server to db-server).
3.  Convert SQL response data to JSON.
4.  Write & compress HTTP response.
5.  Return HTTP response over internet (web-server to browser).

Client Side:
1.  Parse HTTP response.
2.  Render UI.

**Comment by momipsl** [comment] 2015-10-12 14:45
Client side issues have already been identified and fixed:

1.  Parsing job data was slowed down by unnecessary parsing of date fields.  
2.  HTML templates moved to in-line from being defined in a dedicated JS file.

The client side rendering is now < 2 seconds even for large time slices (i.e. > 3M), previously this was approx. 12 seconds.  These changes will be rolled out in next release.

**Comment by momipsl** [comment] 2015-10-12 14:47
Server sides issues were identified in relation to converting SQL response to JSON.  These have been reduced to minimum and will be rolled out in next release.

**Comment by SebastienDenvil** [comment] 2015-10-12 15:18
So we are still in the area of 20 seconds.

Server side phase 1. SQL queries seems slow (6s). A direction to consider for optimisation.
Server side phase 4. What can explain such a long timing 13s? How much data is moved during that phase?

And I am wondering what kind of optimisation has been applied during the last deployment? Because the change was not obvious.

**Comment by momipsl** [comment] 2015-10-12 15:33
Server side phases 1 & 2 can be combined by moving to a lower level db driver, will probably reduce by 50%.

Server side phase 4 (& to a lesser extent sever side phase 1) is partially caused by network issues.  I have the impression that the browser to web-server and web-server to db-server network channels are not optimised for large bandwidths.  In the case of a 3M time-slice we are currently talking about a 3.7MB download which should take a couple of seconds.

**Comment by momipsl** [comment] 2015-10-12 15:37
Regarding previous deployment I trimmed the payload size of a time-slice to the minimum by removing null fields, fields with default values, and unused CV related fields.  I also improved rendering speed by moving to inline pre-compiled HTML templates and by ensuring that all Backbone views were correctly garbage collected.  There is still scope for further trimming of time-slice payload size as job execution end dates are not really required.

**Comment by momipsl** [comment] 2015-10-12 15:43
Thare is another trick available here and that is to simply write the time-slices > 1W to the file system as a compressed JSON file.  This would bypass any need to hit the database at all and could also efficiently leverage both HTTP and browser client caching.  I will need to consider this potential solution a little more carefully but on first thought it seems both feasible & elegant.  A weekly cron-job could update the time-slice files accordingly, the tricky issue is of course related to deltas of very long running simulations.

**Comment by momipsl** [comment] 2015-10-12 16:03
More stats on monitoring time-slice downloads (excluding rendering) from a Chrome browser:

<1W, 159 kB in 1.51s
<2W:  308 kB in 2.37s
<1M:  1.4 mB in 12.19s
<2M:  2.5 mB in 18.55s
<3M:  3.6 mB in 25.87s 
<6M:  4.5 mB in 32.12s
<1Y:   4.5 mB in 32.54s

Chrome supplies finer grained detail on download times: waiting time is the time taken for the server to begin sending back the response, content download time is the time taken for the server to actually return response:

<1W, wait=01.31s  download=0.20s
<2W, wait=01.96s  download=0.32s
<1M, wait=11.16s  download=0.94s
<2M, wait=17.00s  download=1.55s
<3M, wait=24.26s  download=1.60s
<6M, wait=30.08s  download=2.03s
<1Y,  wait=30.51s  download=2.06s

So in each case the wait time is obviously the issue is the time taken for the server to being sending back the response.  IMHO this rules out network issues from web-server to browser.

**Comment by SebastienDenvil** [comment] 2015-10-12 16:06
Agree. network is not responsible for that. Moving 3.7 MB should take less than a tenth of a second. It is 3.7 MB in one file, or in many files. Moving only one file will be much more efficient from the network perspective.

Any idea what causes such a wait time?

**Comment by momipsl** [comment] 2015-10-12 16:54
Wait time is the collective time for the server-side phases 1-4 to complete.  In step 4 we can exclude pure network issues, but we cannot exclude latency due to firewalls, NGinx policies ... etc.

One issue I have in terms of diagnostics is not having local access to a large database, the backups of current production db seem to be OS specific.  Tomorrow I will write a quick test script to generate a large db to replicate the current 3M & 6M timeslice download times.

**Comment by SebastienDenvil** [comment] 2015-10-12 17:32
An OS specific database backups. It sounds weird isn't it?

I dont see the firewalls being responsible for this. NGINX policies sounds like a better suspect. Also I would like to ask again my question. When we have 3.7 MB of data, are they in the same files or in different files? If in many files how much in the 3M case, and how much for the 6M case and so on...

Also interesting would be to have the numbers below but for several cases (1M, 2M, .... 12M). 
The times are related to a 3 month timeslice:

Server side:
1. Issue SQL request over network (web-server to db-server). [6s]
2. Convert SQL response data to JSON. [4s]
3. Write & compress HTTP response. [3s]
4. Return HTTP response over internet (web-server to browser). [13s]

Client Side:
1. Parse HTTP response. [9s]
2. Render UI. [3s]

**Comment by momipsl** [comment] 2015-10-12 18:33
The responses are all the same "file", i.e. the payload of a single HTTP response stream.  When the front loads it first of all downloads the CV's and then the initial time-slice.  The web-service endpoint that is invoked is:

https://prodiguer-test-web.ipsl.fr/api/1/simulation/monitoring/fetch_timeslice?timeslice=1W

**Comment by momipsl** [comment] 2015-10-12 18:34
Re the db backups it is the only explanation I can find for not being able to restore a backup of the prodiguer db on the test server.  But writing a test script will only take an hour or so.

**Comment by momipsl** [comment] 2015-10-12 18:36
Re deeper metrics for the 4 server-side phases: I do not have remote access to db and therefore cannot test locally.  However once I have a test db locally I can give you further stats specific to my environment.

**Closed** 2016-02-04 17:17 UTC
Labels: feature, front end, Priority 1
